---
- name: Upgrade System via dnf
  dnf:
    name: "*"
    state: latest
  become: yes
  when:
    (ansible_facts['distribution'] == "RedHat" and
    ansible_facts['distribution_major_version'] == "8")

- name: Upgrade System via yum
  yum:
    name: "*"
    state: latest
  become: yes
  when:
    (ansible_facts['distribution'] == "RedHat" and
    ansible_facts['distribution_major_version'] == "7") or
    (ansible_facts['distribution'] == "Amazon" and
    ansible_facts['distribution_major_version'] == "2")
