- name: Generate password
  shell: openssl rand -base64 48 | tr -C -d "[:alnum:]" | head -c 24
  register: generated_password

- block:
    - name: Get Token
      command: kinit admin
      args:
        stdin: "{{ admin_pwd }}"

    - name: Modify '{{ secret_target.name }}' password
      command: ipa user-mod '{{ secret_target.name }}' --password
      args:
        stdin: |
          {{ generated_password.stdout }}
          {{ generated_password.stdout }}

    - name: Destroy Token
      command: kdestroy

    - name: Check Token
      command: klist
      register: result
      failed_when: "'krbtgt' in result.stdout"
      changed_when: result.rc != 1

  delegate_to: '{{ groups["ipaserver"][0] }}'
  when: assign_user

- name: Create '{{ secret_target.name }}' secret in Vault
  command:
    argv:
      - vault
      - kv
      - put
      - -address=https://{{ ansible_host }}:8200
      - secrets/{{ secret_target.name }}/
      - "password={{ generated_password.stdout }}"
