# Check if we have access to vault
# Check if secrets with the same names are available in vault
# If they are not available, check if IPA has a user, generate a password, assign password, and save secret to vault.

- name: Log into vault
  command:
    argv:
      - vault
      - login
      - -address=https://{{ ansible_host }}:8200
      - token={{ vault_token.root_token }}

- name: Enable secret KV path
  command:
    argv:
      - vault
      - secrets
      - enable
      - -address=https://{{ ansible_host }}:8200
      - -path=secrets
      - kv
  ignore_errors: true

- name: List current secrets
  command:
    argv:
      - vault
      - list
      - -address=https://{{ ansible_host }}:8200
      - secrets
  register: secret_list
  ignore_errors: true

- include_tasks: assign-password.yml
  vars:
    assign_user: true
  when:
    - "secret_target.name not in secret_list.stdout"
    - '"User login: " ~ secret_target.name in
      hostvars[groups["ipaserver"][0]]["user_list"].stdout'
  loop: "{{ admin_users }}"
  loop_control:
    loop_var: secret_target

- include_tasks: assign-password.yml
  vars:
    assign_user: false
  when:
    - "secret_target.name not in secret_list.stdout"
  loop: "{{ system }}"
  loop_control:
    loop_var: secret_target
