- name: Log into vault
  command:
    argv:
      - vault
      - login
      - -address=https://{{ ansible_host }}:8200
      - token={{ vault_token.root_token }}
  register: login_info

- name: Enable secret KV path
  command:
    argv:
      - vault
      - secrets
      - enable
      - -address=https://{{ ansible_host }}:8200
      - -path=secrets
      - kv
  ignore_errors: true

- name: List current secrets
  command:
    argv:
      - vault
      - list
      - -address=https://{{ ansible_host }}:8200
      - secrets
  register: secret_list
  ignore_errors: true

- name: Write Root CA to secret kv
  shell:
    cat /etc/ipa/ca.crt | vault kv put -address=https://{{ ansible_host }}:8200
    secrets/root-ca/ ca=-
  when: "'root-ca' not in secret_list.stdout"
